### ISSUE TITLE
Add location info to camp descriptions?

### ISSUE THREAD

**Issue by cjdd3b** [striblab/2018-summer-camp-guide#3]
Would be nice to tell where a camp is at a glance. And in some of the aforementioned cases where the map doesn't really give us that context, could helpful to add in the narrative description — assuming we have that info consistently.

**Comment by cjdd3b** [comment]
Example:

![screen shot 2018-03-01 at 10 44 02 am](https://user-images.githubusercontent.com/947791/36857185-7e9ffb7e-1d3d-11e8-9410-819972f024f0.png)

**Comment by zzolo** [comment]
There's a caption with the venue name below the map now (and in the info list on mobile).
