### ISSUE TITLE
Mobile view slightly too wide?

### ISSUE THREAD

**Issue by cjdd3b** [striblab/2018-summer-camp-guide#4]
If you guys are still working on the mobile views (or the responsive view I'm using isn't the right one), just ignore this.

But: It looks like the container might be slightly too wide on the --no-cms render, which leads to a horizontal scrollbar and some weird padding issues on the right and left. The activities checkbox area also is a little tight next to the top slider — but again, ignore this if you guys are still working on mobile.

![image-1 1](https://user-images.githubusercontent.com/947791/36857822-22d5df0a-1d3f-11e8-917c-222dbd493ac6.jpg)

![image-1](https://user-images.githubusercontent.com/947791/36857828-2542dc98-1d3f-11e8-8b87-d42b2d2c75ef.jpg)

**Comment by zzolo** [comment]
These should all be better now, but feel free to re-open if you see more.
