### ISSUE TITLE
Polish: Precache maps?

### ISSUE THREAD

**Issue by cjdd3b** [striblab/2018-summer-camp-guide#5]
This is WAY down the list, but any filtering action results in a bunch of calls to Google Maps to retrieve the new locators, which in turn leads to a slight lagginess on the page. Is there any way to easily precache the maps or do something else to result in fewer network calls? This is particularly noticeable with the sliders.

One option: Have the slider filters apply only on mouseup rather than as the sliders move. This is how the tracking action works in the pull request.

**Comment by zzolo** [comment]
Lazyload images should fix this.
