### ISSUE TITLE
Style map submit success message more elegantly

### ISSUE THREAD

**Issue by stribJamieHutt** [striblab/2018-summer-camp-guide#8]
When a user submits an address, a success response is sent back and printed on the page. It just needs some styling, probably similar to the font size/weight/color or the text above the field. Some padding below would be more comfortable

![image](https://user-images.githubusercontent.com/4742757/36910823-67be8964-1e07-11e8-9f05-d0e2d9539dfc.png)

**Comment by stribBillySteve** [comment]
filters.scss

  .found-address {
    font-size: 0.8em;
    line-height: 1.4em;  
    color: map-get($grays, 'medium');
    padding-bottom: 1em;   
  }

Looks like:

![screen shot 2018-03-02 at 2 47 48 pm](https://user-images.githubusercontent.com/4753168/36921142-dcc028b4-1e28-11e8-9f6b-a9634bd7ae30.png)
